branch-defaults:
  default:
    environment: Bot-env
    group_suffix: null
global:
  application_name: Bot-env
  branch: null
  default_ec2_keyname: pds-token
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
