# Generated by Django 4.2.6 on 2024-05-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_sapf', '0001_initial'),
    ]

    operations = [
    ]
